services:
  - docker

script:
  - docker build -t abdulrahimch/nodejs_prod ./nodejs_backend
  - docker build -t abdulrahimch/angular_prod ./angular_frontend
  # Log in to Docker hub.
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Push images being build into Docker hub.
  - docker push abdulrahimch/nodejs_prod
  - docker push abdulrahimch/angular_prod
